#' Perform score test
#'
#' @description Examine whether a gene is a spatially variable gene specific to a cell type using score test for all celltype-gene pairs.
#'
#' @importFrom parallel detectCores makeCluster stopCluster
#' @importFrom doParallel registerDoParallel
#' @importFrom foreach foreach %dopar%
#' @importFrom iterators iter
#'
#' @param object An \code{\link[=mcube-class]{mcube}} object with fitted results of the null model.
#' @param kernels_list A list containing the kernel matrices for testing.
#' If `NULL`, the kernel matrices will be generated by the function `mcubeKernel`. Default is `NULL`.
#' @param standardize A logical value.
#' If `TRUE`, the coordinates will be standardized. Default is `TRUE`.
#' @param keep_kernels A logical value indicating whether to store kernels after testing. Default is `FALSE`.
#' @param num_workers A positive integer.
#' The number of workers for parallel computing. Default is 1.
#' @param num_threads A positive integer.
#' The number of threads per worker to use for BLAS operations.
#'
#' @return An \code{\link[=mcube-class]{mcube}} object with testing results for all celltype-gene pairs.
#'
#' @export
mcubeTest <- function(
    object, kernels_list = NULL, standardize = TRUE,
    keep_kernels = FALSE, num_workers = 1L, num_threads = NULL) {
  if (is.null(kernels_list)) {
    num_kernels <- 2
    length_scale_seq <- c(1, sqrt(2)) *
      mcubeLengthScale(object@coordinates, standardize = standardize)
    kernels_list <- mapply(
      FUN = function(kernel_type, length_scale) {
        mcubeKernel(
          coordinates = object@coordinates,
          spots = object@spots,
          standardize = standardize,
          kernel_type = kernel_type,
          length_scale = length_scale
        )
      },
      kernel_type = c(
        "linear",
        rep("Gaussian", num_kernels), rep("Gaussian_transformed", num_kernels)
      ),
      length_scale = c(0, length_scale_seq, length_scale_seq),
      SIMPLIFY = FALSE
    )
    names(kernels_list) <- c(
      "linear",
      paste0("Gaussian_", 1:num_kernels),
      paste0("Gaussian_transformed_", 1:num_kernels)
    )
  } else if (!is.list(kernels_list)) {
    stop("mcubeTest: Please store the kernel matrices in a list!") # End
  } else if (!all(
    sapply(kernels_list,
           FUN = function(kernel_mat) {
             identical(rownames(object@counts), rownames(kernel_mat)) &&
               identical(rownames(object@counts), colnames(kernel_mat))
           }
    )
  )) {
    stop("mcubeTest: The rownames and colnames of the kernel matrices must match the sample names of the counts!") # End
  } else {
    if (is.null(names(kernels_list)) || all(names(kernels_list) != "")) {
      names(kernels_list) <- paste0("kernel_", length(object@kernels))
    }
  }

  if (num_workers == 1) {
    pvalues <- list()
    for (i in 1:nrow(object@celltype_gene_test_pairs)) {
      pvalues[[i]] <- tryCatch(
        mcubeTestSinglePairMultiKernels(
          null_model_results = object@null_models[[i]],
          X = object@covariates[object@spots, , drop = FALSE],
          kernels_list = kernels_list,
          celltype = object@celltype_gene_test_pairs$celltype[i],
          num_threads = num_threads
        ),
        error = function(e) {
          return(e)
        }
      )
    }
  } else if (num_workers > 1) {
    X <- object@covariates[object@spots, , drop = FALSE]

    num_cores <- parallel::detectCores(logical = FALSE)
    if (num_cores <= 2) {
      stop("Number of detected physical cores is not greater than 2!")
    }
    message("Number of physical cores: ", num_cores, ".")

    num_workers <- ifelse(
      num_workers < num_cores, num_workers, num_cores - 1L
    )
    message("Number of workers: ", num_workers, ".")

    if (is.null(num_threads)) {
      num_threads <- 1L
    }
    message("Number of thread(s) per worker: ", num_threads, ".")

    if (num_workers * num_threads >= num_cores) {
      stop("num_workers * num_threads >= num_cores will cause resource contention!")
    }

    cl <- parallel::makeCluster(num_workers)
    doParallel::registerDoParallel(cl)

    pvalues <- foreach::foreach(
      null_model_results_i = iterators::iter(object@null_models),
      celltype_i = iterators::iter(object@celltype_gene_test_pairs$celltype),
      .export = c(
        "mcubeTestSinglePairSingleKernel",
        "mcubeTestSinglePairMultiKernels",
        "ACAT"
      ),
      .errorhandling = "pass"
    ) %dopar% {
      mcubeTestSinglePairMultiKernels(
        null_model_results = null_model_results_i,
        X = X,
        kernels_list = kernels_list,
        celltype = celltype_i,
        num_threads = num_threads
      )
    }

    parallel::stopCluster(cl)
  } else {
    stop("mcubeTest: max_cores must be a positive integer!") # End
  }

  # Remove the error results
  error_vec <- sapply(
    pvalues,
    FUN = function(x) {
      inherits(x, "error")
    }
  )
  if (any(error_vec)) {
    object@null_models <- object@null_models[!error_vec]
    object@celltype_gene_test_pairs <-
      object@celltype_gene_test_pairs[!error_vec, , drop = FALSE]
    pvalues <- pvalues[!error_vec]
  }

  object@pvalues <- mapply(
    FUN = function(pvalues_df, genes) {
      rownames(pvalues_df) <- genes
      return(pvalues_df)
    },
    pvalues_df = split(
      as.data.frame(do.call("rbind", pvalues)),
      object@celltype_gene_test_pairs$celltype
    ),
    genes = split(
      object@celltype_gene_test_pairs$gene,
      object@celltype_gene_test_pairs$celltype
    ),
    SIMPLIFY = FALSE
  )

  if (keep_kernels) {
    object@kernels <- kernels_list
  } else {
    object@kernels <- list("Please set keep_kernels = TRUE if you want to keep the kernels!")
  }

  return(object)
}

#' Perform score test for a single pair of cell type and gene with multiple kernels
#'
#' @description
#' Examine whether a gene is a spatially variable gene specific to a cell type with multiple kernels.
#' The obtained p-values will be combined using the Cauchy distribution.
#'
#' @importFrom RhpcBLASctl blas_set_num_threads
#'
#' @param null_model_results A list containing the fitted results of the null model.
#' @param X A numeric matrix containing covariates of all spots.
#' Each row represents a spot and each column represents a covariate.
#' @param kernels_list A list containing the kernel matrices for testing.
#' @param celltype A character specifying the cell type to test.
#' @param num_threads A positive integer.
#' The number of threads per worker to use for BLAS operations.
#'
#' @return A data.frame containing the test results.
#'
#' @export
mcubeTestSinglePairMultiKernels <- function(
    null_model_results, X, kernels_list, celltype,
    num_threads = NULL) {
  if (!is.null(num_threads)) {
    num_threads <- RhpcBLASctl::blas_set_num_threads(num_threads)
  }

  if (!(celltype %in% null_model_results$celltype)) {
    stop("mcubeTestSinglePairMultiKernels: cell_type is not found in the null model results!") # End
  }

  kernels_list <- lapply(
    kernels_list,
    FUN = function(kernel_mat) {
      kernel_mat[null_model_results$spots, null_model_results$spots, drop = FALSE]
    }
  )
  X <- X[null_model_results$spots, , drop = FALSE]

  # Compute the projection matrix
  Sigma_inv_X_mat <- null_model_results$Sigma_inv * X
  X_t_Sigma_inv_X_mat <- crossprod(X, Sigma_inv_X_mat)
  P_mat <- diag(null_model_results$Sigma_inv) -
    tcrossprod(
      Sigma_inv_X_mat %*% chol2inv(chol(X_t_Sigma_inv_X_mat)),
      Sigma_inv_X_mat
    )
  P_Y_tilde <- as.vector(P_mat %*% null_model_results$Y_tilde)

  pvalues <- sapply(
    kernels_list,
    FUN = function(kernel_mat) {
      mcubeTestSinglePairSingleKernel(
        null_model_results, P_mat, P_Y_tilde,
        kernel_mat, celltype
      )
    }
  )

  if (length(kernels_list) > 1) {
    # Combine p-values using the Cauchy distribution
    pvalues <- c(pvalues, combined_pvalue = ACAT(pvalues))
  }
  names(pvalues)[1:length(kernels_list)] <- names(kernels_list)

  return(pvalues)
}

#' Perform score test for a single pair of cell type and gene with a single kernel
#'
#' @description Examine whether a gene is a spatially variable gene specific to a cell type with a single kernel.
#'
#' @importFrom stats pchisq
#'
#' @param null_model_results A list containing the fitted results of the null model.
#' @param P_mat A numeric projection matrix.
#' @param P_Y_tilde A numeric vector contraining the value of P %*% Y_tilde.
#' @param kernel_mat A kernel_mat for testing.
#' @param celltype A character specifying the cell type to test.
#'
#' @return A p-value.
#'
#' @export
mcubeTestSinglePairSingleKernel <- function(
    null_model_results, P_mat, P_Y_tilde,
    kernel_mat, celltype) {
  if (!(celltype %in% null_model_results$celltype)) {
    return(NULL)
  }

  membership <- null_model_results$membership[, celltype]
  kernel_mat <- kernel_mat * (membership %o% membership)
  P_kernel_mat <- P_mat %*% kernel_mat

  teststat_var <- 0.5 * sum(P_kernel_mat^2) # variance of test statistic
  teststat_mean <- 0.5 * sum(diag(P_kernel_mat)) # mean of test statistic
  scaled_para <- 0.5 * teststat_var / teststat_mean # scaled parameter
  df_para <- 2.0 * teststat_mean^2 / teststat_var # degrees of freedom

  P_kernel_P_Y_tilde <- as.vector(P_kernel_mat %*% P_Y_tilde)
  teststat <- 0.5 *
    sum(null_model_results$Y_tilde * P_kernel_P_Y_tilde) # test statistic

  pvalue <- stats::pchisq(q = teststat / scaled_para, df = df_para, lower.tail = FALSE)

  return(pvalue)
}
