#' Directly integrate MCube with the cell type deconvolution results from RCTD
#'
#' @importClassesFrom spacexr RCTD SpatialRNA Reference
#'
#' @param RCTD_object An S4 class used to represent spatial transcriptomic data and single-cell RNA-sequencing data,
#' run the RCTD algorithm and store the cell type deconvolution results.
#' @param RCTD_mode A character indicating in which mode to `RCTD`, corresponding to the `doublet_mode` argument in the `spacexr::run.RCTD()` function.
#' The choice of the `RCTD` mode depends on the resolution of the ST data and determines the analysis strategy of `MCube`.
#' For the low resolution ST data, such as the Visium data, we recommend to use `full` mode,
#' and `MCube` will analyze all the cell types of interest together and store the results in a single \code{\linkS4class{mcube}} object.
#' For the high resolution ST data, such as the Visium HD and Xenium data, we recommend to use `doublet` mode.
#' Then, `MCube` will analyze each cell type separately using the spots with a high probability of containing the target cell type according to the deconvolution results.
#' The results will be stored in a list of \code{\linkS4class{mcube}} objects, each corresponding to a cell type.
#' @param sample_size_max A positive integer.
#' The high resolution ST data may contain over 100K samples in total and lead to high computational costs.
#' Therefore, in the `doublet` mode, we randomly sample `sample_size_max` spots to analyze for the cell type with valid spots greater than `sample_size_max`.
#' @param covariates A matrix.
#' Each row represents a spot and each column represents a covariate.
#' @param batch_id A character/factor vector indicating which batch each spot comes from.
#' It's applicable to the case of multiple samples/replicates/slices and specific gene platform effects required.
#' If `NULL`, all spots will be assumed to come from the same batch and share the same gene platform effects. Default is `NULL`.
#' @param spots A character vector specifying the names of spots to analyze.
#' @param library_size_min A numeric value.
#' The minimum library size to filter out spots.
#' @param celltype_test A character vector specifying the cell types to test.
#' If `NULL`, all cell types that pass the filtering criteria will be included. Default is `NULL`.
#' @param gene_test A character vector specifying the genes to test.
#' If `NULL`, all genes that pass the filtering criteria will be included. Default is `NULL`.
#' @param celltype_threshold A numeric value.
#' The minimum proportion sum across spots of a cell type to be considered.
#' @param gene_threshold A numeric value.
#' The minimum average expression level across spots of a gene to be considered.
#' @param proportion_threshold A numeric value between 0 and 1.
#' The minimum proportion of a cell type to be considered at a spot.
#' If not specified, it will be set as 0.1 in the `full` mode and 0.01 in the `doublet` mode.
#' @param reference_threshold_test A numeric value between 0 and 1.
#' The minimum relative expression level of a gene to be considered for a cell type in testing.
#' @param reference_threshold_fit A numeric value between 0 and 1.
#' The minimum relative expression level of a gene to be considered for a cell type when fitting the null models.
#' @param safeguard A numeric value.
#' A small positive number to avoid numerical issues when computing the inverse of a matrix for fitting the null models.
#' @param iter_max A positive integer.
#' The maximum number of iterations for the optimization algorithm when fitting the null models.
#' @param tol A numeric value.
#' The convergence criteria for the optimization algorithm when fitting the null models.
#' @param verbose A logical value.
#' Whether to print the progress of the optimization algorithm when fitting the null models. Default is FALSE.
#' @param kernels_list A list containing the kernel matrices for testing.
#' If `NULL`, the kernel matrices will be generated by the function `mcubeKernel`. Default is `NULL`.
#' @param standardize A logical value.
#' If `TRUE`, the coordinates will be standardized. Default is `TRUE`.
#' @param keep_kernels A logical value indicating whether to store kernels after testing. Default is `FALSE`.
#' @param num_workers A positive integer.
#' The number of worker processes for parallel computing. Default is 1.
#' @param num_threads A positive integer.
#' The number of threads on BLAS per worker.
#' @param shared_memory A logical value.
#' If `TRUE`, the large kernel matrices will be handled through memory-mapping to binary files on disk.
#' @param project A character recording the name of the project.
#'
#' @return A single \code{\linkS4class{mcube}} object if `RCTD_mode` is `full`,
#' and a list of \code{\linkS4class{mcube}} objects with each element corresponding to a cell type if `RCTD_mode` is `doublet`.
#'
#' @export
mcubeRCTD <- function(
    RCTD_object, RCTD_mode, sample_size_max = 5000L,
    covariates = NULL, batch_id = NULL,
    spots = NULL, library_size_min = 10,
    celltype_test = NULL, gene_test = NULL,
    celltype_threshold = 100, gene_threshold = 5e-5,
    proportion_threshold = NULL, reference_threshold_test = 0.5,
    reference_threshold_fit = 0.25,
    safeguard = 1e-6, iter_max = 100L, tol = 1e-6, verbose = FALSE,
    kernels_list = NULL, standardize = TRUE, keep_kernels = FALSE,
    num_workers = 1L, num_threads = NULL, shared_memory = FALSE,
    project = "MCube") {
  # Inherit the cell type deconvolution results from RCTD
  spot_names <- colnames(RCTD_object@spatialRNA@counts)
  weights_RCTD <- as.matrix(RCTD_object@results$weights)
  weights_rowsums_RCTD <- rowSums(weights_RCTD)
  spot_effects_RCTD <- log(weights_rowsums_RCTD)
  names(spot_effects_RCTD) <- rownames(weights_RCTD)

  if (RCTD_mode == "full") {
    # Create an MCube object
    if (!is.null(covariates)) {
      if (all(spot_names %in% rownames(covariates))) {
        covariates <- covariates[spot_names, , drop = FALSE]
      } else {
        stop("The row names of the covariate matrix must contain all the spots in the RCTD object.")
      }
    }
    if (!is.null(batch_id)) {
      if (all(spot_names %in% names(batch_id))) {
        batch_id <- batch_id[spot_names]
      } else {
        stop("The name of the batch id vector must contain all the spots in the RCTD object.")
      }
    }
    if (is.null(proportion_threshold)) {
      proportion_threshold <- 0.1
    }
    mcube_object <- createMCube(
      counts = t(as.matrix(RCTD_object@originalSpatialRNA@counts[, spot_names])),
      coordinates = as.matrix(RCTD_object@spatialRNA@coords),
      proportions = weights_RCTD / weights_rowsums_RCTD,
      library_sizes = RCTD_object@spatialRNA@nUMI,
      covariates = covariates,
      batch_id = batch_id,
      reference = t(RCTD_object@cell_type_info$info[[1]]),
      used_for_deconvolution = rownames(RCTD_object@spatialRNA@counts),
      spots = spots,
      library_size_min = library_size_min,
      spot_effects = spot_effects_RCTD,
      platform_effects = NULL,
      celltype_test = celltype_test,
      gene_test = gene_test,
      celltype_threshold = celltype_threshold,
      gene_threshold = gene_threshold,
      proportion_threshold = proportion_threshold,
      reference_threshold = reference_threshold_test,
      project = project
    )

    # Fit the null models
    mcube_object <- mcubeFitNull(
      mcube_object,
      reference_threshold = reference_threshold_fit,
      safeguard = safeguard,
      iter_max = iter_max,
      tol = tol,
      verbose = verbose,
      num_workers = num_workers,
      num_threads = num_threads
    )

    # Perform the statistical testing
    mcube_object <- mcubeTest(
      mcube_object,
      kernels_list = kernels_list,
      standardize = standardize,
      keep_kernels = keep_kernels,
      num_workers = num_workers,
      num_threads = num_threads,
      shared_memory = shared_memory
    )

    return(mcube_object)
  } else if (RCTD_mode == "doublet") {
    if (!is.null(covariates)) {
      if (all(spot_names %in% rownames(covariates))) {
        covariates <- covariates[spot_names, , drop = FALSE]
      } else {
        stop("The row names of the covariate matrix must contain all the spots in the RCTD object.")
      }
    }
    if (!is.null(batch_id)) {
      if (all(spot_names %in% names(batch_id))) {
        batch_id <- batch_id[spot_names]
      } else {
        stop("The name of the batch id vector must contain all the spots in the RCTD object.")
      }
    }
    proportions_RCTD <- weights_RCTD / weights_rowsums_RCTD
    if (is.null(proportion_threshold)) {
      proportion_threshold <- 0.01
    }
    if (is.null(celltype_test)) {
      celltype_test <- colnames(proportions_RCTD)
    } else {
      celltype_test <- intersect(colnames(proportions_RCTD), celltype_test)
    }
    doublet_results_RCTD <- RCTD_object@results$results_df

    i <- 0 # Cell type counter
    mcube_list <- list() # A list to store the MCube objects for each cell type
    for (celltype in celltype_test) {
      spots_used <- rownames(doublet_results_RCTD)[
        ((doublet_results_RCTD$spot_class == "singlet" |
            doublet_results_RCTD$spot_class == "doublet_uncertain") &
           doublet_results_RCTD$first_type == celltype
        ) |
          (doublet_results_RCTD$spot_class == "doublet_certain" &
             (doublet_results_RCTD$first_type == celltype |
                doublet_results_RCTD$second_type == celltype))
      ]

      if (length(spots_used) > 0 & sum(proportions_RCTD[spots_used, celltype]) > celltype_threshold) {
        i <- i + 1

        if (length(spots_used) > sample_size_max) {
          spots_used <- sample(spots_used, size = sample_size_max, replace = FALSE)
        }

        # Create an MCube object for the cell type
        mcube_object <- createMCube(
          counts = t(as.matrix(RCTD_object@originalSpatialRNA@counts[, spots_used])),
          coordinates = as.matrix(RCTD_object@spatialRNA@coords[spots_used, ]),
          proportions = proportions_RCTD[spots_used, ],
          library_sizes = RCTD_object@spatialRNA@nUMI[spots_used],
          covariates = covariates[spots_used, ],
          batch_id = batch_id[spots_used],
          reference = t(RCTD_object@cell_type_info$info[[1]]),
          used_for_deconvolution = rownames(RCTD_object@spatialRNA@counts),
          spots = spots,
          library_size_min = library_size_min,
          spot_effects = spot_effects_RCTD[spots_used],
          platform_effects = NULL,
          celltype_test = celltype,
          gene_test = gene_test,
          celltype_threshold = celltype_threshold,
          gene_threshold = gene_threshold,
          proportion_threshold = proportion_threshold,
          reference_threshold = reference_threshold_test,
          project = paste0(project, "_", celltype)
        )

        # Fit the null models
        mcube_object <- mcubeFitNull(
          mcube_object,
          reference_threshold = reference_threshold_fit,
          safeguard = safeguard,
          iter_max = iter_max,
          tol = tol,
          verbose = verbose,
          num_workers = num_workers,
          num_threads = num_threads
        )

        # Perform the statistical testing
        mcube_object <- mcubeTest(
          mcube_object,
          kernels_list = kernels_list,
          standardize = standardize,
          keep_kernels = keep_kernels,
          num_workers = num_workers,
          num_threads = num_threads,
          shared_memory = shared_memory
        )

        message("MCube analysis for ", celltype, " completed!")

        mcube_list[[i]] <- mcube_object
        names(mcube_list)[i] <- celltype
      }
    }
    return(mcube_list)
  } else {
    stop("Invalid RCTD_mode! Please set RCTD_mode = doublet or full.")
  }
}
